{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "     Color  Radius (cm)  Weight (grams) Fruit (class)\n",
      "0   Yellow          2.3              61         Lemon\n",
      "1   Yellow          4.8              75         Apple\n",
      "2    Green          3.6             173          Pear\n",
      "3   Yellow          2.6              58         Lemon\n",
      "4   Yellow          2.1              40         Lemon\n",
      "5    Green          3.0              86         Apple\n",
      "6   Yellow          3.1              60         Lemon\n",
      "7   Yellow          5.2             141          Pear\n",
      "8    Green          2.5              70         Apple\n",
      "9   Yellow          3.2              79         Apple\n",
      "10     Red          3.9             101         Apple\n",
      "11   Green          2.4              62         Lemon\n",
      "12   Green          4.6             152          Pear\n",
      "13   Green          4.3             133          Pear\n",
      "14  Yellow          4.1               0         Lemon\n",
      "15  Yellow          2.9              53         Lemon\n",
      "16   Green          4.5             110          Pear\n",
      "17  Yellow          2.3              60         Lemon\n",
      "18     Red          3.7             101         Apple\n",
      "19  Yellow          4.1             135          Pear\n",
      "20  Yellow          2.4              63         Lemon\n",
      "21  Yellow          2.1              64         Apple\n",
      "22   Green          2.7              73         Apple\n",
      "23     Red          3.8              80         Apple\n",
      "24   Green          4.2             126          Pear\n",
      "25  Yellow          3.5              98         Apple\n",
      "26  Yellow          3.2              62         Lemon\n",
      "27   Green          2.5              65         Lemon\n",
      "28  Yellow          2.1              41         Lemon\n",
      "29   Green          3.1              85         Apple\n",
      "30  Yellow          0.0             137          Pear\n",
      "31  Yellow          5.2             142          Pear\n",
      "    Color  Radius (cm)  Weight (grams)  Predicted (class) Original (class)\n",
      "0  Yellow          2.5              64                NaN            Lemon\n",
      "1   Green          4.2              90                NaN             Pear\n",
      "2   Green          3.2              95                NaN             Pear\n",
      "3     Red          2.9              65                NaN            Apple\n",
      "4  Yellow          2.9              60                NaN            Lemon\n"
     ]
    }
   ],
   "source": [
    "import pandas as pd\n",
    "train_data = pd.read_csv(\"traindata.csv\", header = 0)\n",
    "test_data = pd.read_csv(\"testdata.csv\", header = 0)\n",
    "\n",
    "print(train_data)\n",
    "print(test_data)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Test Data is    Green  Red  Yellow  Radius (cm)  Weight (grams)  Predicted (class)  \\\n",
      "0      0    0       1          2.5              64                NaN   \n",
      "1      1    0       0          4.2              90                NaN   \n",
      "2      1    0       0          3.2              95                NaN   \n",
      "3      0    1       0          2.9              65                NaN   \n",
      "4      0    0       1          2.9              60                NaN   \n",
      "\n",
      "  Original (class)  \n",
      "0            Lemon  \n",
      "1             Pear  \n",
      "2             Pear  \n",
      "3            Apple  \n",
      "4            Lemon  \n",
      "train data is     Green  Red  Yellow  Radius (cm)  Weight (grams) Fruit (class)\n",
      "0       0    0       1          2.3            61.0         Lemon\n",
      "1       0    0       1          4.8            75.0         Apple\n",
      "2       1    0       0          3.6           173.0          Pear\n",
      "3       0    0       1          2.6            58.0         Lemon\n",
      "4       0    0       1          2.1            40.0         Lemon\n",
      "5       1    0       0          3.0            86.0         Apple\n",
      "6       0    0       1          3.1            60.0         Lemon\n",
      "7       0    0       1          5.2           141.0          Pear\n",
      "8       1    0       0          2.5            70.0         Apple\n",
      "9       0    0       1          3.2            79.0         Apple\n",
      "10      0    1       0          3.9           101.0         Apple\n",
      "11      1    0       0          2.4            62.0         Lemon\n",
      "12      1    0       0          4.6           152.0          Pear\n",
      "13      1    0       0          4.3           133.0          Pear\n",
      "15      0    0       1          2.9            53.0         Lemon\n",
      "16      1    0       0          4.5           110.0          Pear\n",
      "17      0    0       1          2.3            60.0         Lemon\n",
      "18      0    1       0          3.7           101.0         Apple\n",
      "19      0    0       1          4.1           135.0          Pear\n",
      "20      0    0       1          2.4            63.0         Lemon\n",
      "21      0    0       1          2.1            64.0         Apple\n",
      "22      1    0       0          2.7            73.0         Apple\n",
      "23      0    1       0          3.8            80.0         Apple\n",
      "24      1    0       0          4.2           126.0          Pear\n",
      "25      0    0       1          3.5            98.0         Apple\n",
      "26      0    0       1          3.2            62.0         Lemon\n",
      "27      1    0       0          2.5            65.0         Lemon\n",
      "28      0    0       1          2.1            41.0         Lemon\n",
      "29      1    0       0          3.1            85.0         Apple\n",
      "31      0    0       1          5.2           142.0          Pear\n"
     ]
    }
   ],
   "source": [
    "import numpy as np\n",
    "# drop duplicated rows\n",
    "train_data = train_data.drop_duplicates()\n",
    "#print(train_data)\n",
    "    \n",
    "# replace zeros entries with np.nan\n",
    "train_data = train_data.replace(0,np.nan)\n",
    "train_data = train_data.dropna() # drop all nan entiries \n",
    "#print(train_data)\n",
    "\n",
    "newCols = pd.get_dummies(train_data.iloc[:,0]) \n",
    "train_data = pd.concat([newCols, train_data], axis=1) # add them to the transfomed columns to the beggining  of the data frame\n",
    "train_data = train_data.drop(train_data.columns[3], axis = 1) # drop nominal column (color)   \n",
    "\n",
    "# drop duplicated rows\n",
    "test_data= test_data.drop_duplicates()\n",
    "\n",
    "# transform the nominal feature (color) to dummy\n",
    "newCols=pd.get_dummies(test_data.iloc[:,0]) \n",
    "test_data = pd.concat([newCols, test_data], axis=1) # add them to the transfomed columns to the beggining  of the data frame\n",
    "test_data= test_data.drop(test_data.columns[3], axis = 1) # drop nominal column (color)  \n",
    "\n",
    "print(\"Test Data is\", test_data)\n",
    "print(\"train data is\", train_data)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "['Green', 'Red', 'Yellow', 'Radius (cm)', 'Weight (grams)', 'Fruit (class)']\n",
      "0     Lemon\n",
      "1     Apple\n",
      "2      Pear\n",
      "3     Lemon\n",
      "4     Lemon\n",
      "5     Apple\n",
      "6     Lemon\n",
      "7      Pear\n",
      "8     Apple\n",
      "9     Apple\n",
      "10    Apple\n",
      "11    Lemon\n",
      "12     Pear\n",
      "13     Pear\n",
      "15    Lemon\n",
      "16     Pear\n",
      "17    Lemon\n",
      "18    Apple\n",
      "19     Pear\n",
      "20    Lemon\n",
      "21    Apple\n",
      "22    Apple\n",
      "23    Apple\n",
      "24     Pear\n",
      "25    Apple\n",
      "26    Lemon\n",
      "27    Lemon\n",
      "28    Lemon\n",
      "29    Apple\n",
      "31     Pear\n",
      "Name: Fruit (class), dtype: object\n",
      "['Lemon' 'Apple' 'Pear']\n",
      "['Green', 'Red', 'Yellow', 'Radius (cm)', 'Weight (grams)', 'Predicted (class)', 'Original (class)']\n"
     ]
    }
   ],
   "source": [
    "Atrributes_train = list(train_data.columns)\n",
    "print(Atrributes_train)\n",
    "classes = train_data[Atrributes_train[-1]]\n",
    "print(classes)\n",
    "classes_name = classes.unique()\n",
    "print(classes_name)\n",
    "\n",
    "Atrributes_test = list(test_data.columns)\n",
    "print(Atrributes_test)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "    Green  Red  Yellow  Radius (cm)  Weight (grams)\n",
      "0     0.0  0.0     1.0     0.064516        0.157895\n",
      "1     0.0  0.0     1.0     0.870968        0.263158\n",
      "2     1.0  0.0     0.0     0.483871        1.000000\n",
      "3     0.0  0.0     1.0     0.161290        0.135338\n",
      "4     0.0  0.0     1.0     0.000000        0.000000\n",
      "5     1.0  0.0     0.0     0.290323        0.345865\n",
      "6     0.0  0.0     1.0     0.322581        0.150376\n",
      "7     0.0  0.0     1.0     1.000000        0.759398\n",
      "8     1.0  0.0     0.0     0.129032        0.225564\n",
      "9     0.0  0.0     1.0     0.354839        0.293233\n",
      "10    0.0  1.0     0.0     0.580645        0.458647\n",
      "11    1.0  0.0     0.0     0.096774        0.165414\n",
      "12    1.0  0.0     0.0     0.806452        0.842105\n",
      "13    1.0  0.0     0.0     0.709677        0.699248\n",
      "15    0.0  0.0     1.0     0.258065        0.097744\n",
      "16    1.0  0.0     0.0     0.774194        0.526316\n",
      "17    0.0  0.0     1.0     0.064516        0.150376\n",
      "18    0.0  1.0     0.0     0.516129        0.458647\n",
      "19    0.0  0.0     1.0     0.645161        0.714286\n",
      "20    0.0  0.0     1.0     0.096774        0.172932\n",
      "21    0.0  0.0     1.0     0.000000        0.180451\n",
      "22    1.0  0.0     0.0     0.193548        0.248120\n",
      "23    0.0  1.0     0.0     0.548387        0.300752\n",
      "24    1.0  0.0     0.0     0.677419        0.646617\n",
      "25    0.0  0.0     1.0     0.451613        0.436090\n",
      "26    0.0  0.0     1.0     0.354839        0.165414\n",
      "27    1.0  0.0     0.0     0.129032        0.187970\n",
      "28    0.0  0.0     1.0     0.000000        0.007519\n",
      "29    1.0  0.0     0.0     0.322581        0.338346\n",
      "31    0.0  0.0     1.0     1.000000        0.766917\n",
      "0     Lemon\n",
      "1     Apple\n",
      "2      Pear\n",
      "3     Lemon\n",
      "4     Lemon\n",
      "5     Apple\n",
      "6     Lemon\n",
      "7      Pear\n",
      "8     Apple\n",
      "9     Apple\n",
      "10    Apple\n",
      "11    Lemon\n",
      "12     Pear\n",
      "13     Pear\n",
      "15    Lemon\n",
      "16     Pear\n",
      "17    Lemon\n",
      "18    Apple\n",
      "19     Pear\n",
      "20    Lemon\n",
      "21    Apple\n",
      "22    Apple\n",
      "23    Apple\n",
      "24     Pear\n",
      "25    Apple\n",
      "26    Lemon\n",
      "27    Lemon\n",
      "28    Lemon\n",
      "29    Apple\n",
      "31     Pear\n",
      "Name: Fruit (class), dtype: object\n",
      "test_data\n",
      "   Green  Red  Yellow  Radius (cm)  Weight (grams)\n",
      "0    0.0  0.0     1.0     0.000000        0.114286\n",
      "1    1.0  0.0     0.0     1.000000        0.857143\n",
      "2    1.0  0.0     0.0     0.411765        1.000000\n",
      "3    0.0  1.0     0.0     0.235294        0.142857\n",
      "4    0.0  0.0     1.0     0.235294        0.000000\n",
      "0    Lemon\n",
      "1     Pear\n",
      "2     Pear\n",
      "3    Apple\n",
      "4    Lemon\n",
      "Name: Original (class), dtype: object\n"
     ]
    }
   ],
   "source": [
    "from sklearn import preprocessing\n",
    "\n",
    "#train data\n",
    "label_encoder = preprocessing.LabelEncoder()\n",
    "for attribute in Atrributes_train[:-1] :\n",
    "    if(train_data[attribute].dtypes == 'object') :\n",
    "        train_data[attribute]= label_encoder.fit_transform(train_data[attribute]) \n",
    "    else :\n",
    "        normalized_df=(train_data[attribute]-train_data[attribute].min())/(train_data[attribute].max()-train_data[attribute].min())\n",
    "        train_data[attribute]= normalized_df\n",
    "    \n",
    "X_train = train_data[Atrributes_train[:-1]]\n",
    "#X_train = preprocessing.normalize(X_train)\n",
    "#X_train['Radius (cm)'] = preprocessing.normalize(X_train['Radius (cm)'])\n",
    "Y_train = train_data[Atrributes_train[-1]]\n",
    "print(X_train)\n",
    "print(Y_train)\n",
    "\n",
    "#test data\n",
    "print(\"test_data\")\n",
    "label_encoder = preprocessing.LabelEncoder()\n",
    "for attribute in Atrributes_test[:-2] :\n",
    "    if(test_data[attribute].dtypes == 'object') :\n",
    "        test_data[attribute]= label_encoder.fit_transform(test_data[attribute])\n",
    "    else :\n",
    "        normalized_df=(test_data[attribute]-test_data[attribute].min())/(test_data[attribute].max()-test_data[attribute].min())\n",
    "        test_data[attribute]= normalized_df\n",
    "    \n",
    "X_test = test_data[Atrributes_test[:-2]]\n",
    "Y_test = test_data[Atrributes_test[-1]]\n",
    "print(X_test)\n",
    "print(Y_test)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "1\n",
      "['Apple' 'Pear' 'Pear' 'Apple' 'Lemon']\n",
      "2\n",
      "['Apple' 'Pear' 'Pear' 'Apple' 'Lemon']\n",
      "3\n",
      "['Lemon' 'Pear' 'Pear' 'Apple' 'Lemon']\n",
      "4\n",
      "['Lemon' 'Pear' 'Pear' 'Apple' 'Lemon']\n",
      "5\n",
      "['Lemon' 'Pear' 'Pear' 'Apple' 'Lemon']\n",
      "6\n",
      "['Lemon' 'Pear' 'Pear' 'Apple' 'Lemon']\n",
      "7\n",
      "['Lemon' 'Pear' 'Pear' 'Apple' 'Lemon']\n",
      "8\n",
      "['Lemon' 'Pear' 'Pear' 'Apple' 'Lemon']\n",
      "9\n",
      "['Lemon' 'Pear' 'Pear' 'Lemon' 'Lemon']\n",
      "10\n",
      "['Lemon' 'Pear' 'Pear' 'Apple' 'Lemon']\n",
      "11\n",
      "['Lemon' 'Pear' 'Pear' 'Lemon' 'Lemon']\n"
     ]
    }
   ],
   "source": [
    "from sklearn.neighbors import KNeighborsClassifier\n",
    "\n",
    "for n in range(1,12) :\n",
    "    print(n)\n",
    "    knn = KNeighborsClassifier(n_neighbors=n)\n",
    "    knn.fit(X_train, Y_train)\n",
    "    y_pred = knn.predict(X_test)\n",
    "    print(y_pred)\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "[[0 1 0]\n",
      " [0 2 0]\n",
      " [0 0 2]]\n"
     ]
    }
   ],
   "source": [
    "from sklearn.metrics import confusion_matrix\n",
    "cm=confusion_matrix(Y_test,y_pred)\n",
    "print(cm)\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 7,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "              precision    recall  f1-score   support\n",
      "\n",
      "       Apple       0.00      0.00      0.00         1\n",
      "       Lemon       0.67      1.00      0.80         2\n",
      "        Pear       1.00      1.00      1.00         2\n",
      "\n",
      "    accuracy                           0.80         5\n",
      "   macro avg       0.56      0.67      0.60         5\n",
      "weighted avg       0.67      0.80      0.72         5\n",
      "\n"
     ]
    }
   ],
   "source": [
    "from sklearn.metrics import classification_report\n",
    "print(classification_report(Y_test, y_pred, zero_division=0))"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.8.3"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 4
}
